runtime: python
env: flex
service: ethereum-etl
entrypoint: gunicorn -b :$PORT main:app

beta_settings:
  cloud_sql_instances: origin-214503:us-west1:dshop-mainnet0

runtime_config:
  python_version: 3

# Intentionally limit the max number of instances to 1 so that no more
# than 1 etl job runs in parallel.
manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
